### ISSUE TITLE
Single booking retrieve is not working even when mocked data

### ISSUE THREAD

**Issue by clucasalcantara** [hexis-hub/hexis-bookings-api#5]
For some reason, we aren't able to retrieve a single booking object through de endpoint `/bookings/{id}`

**Comment by clucasalcantara** [comment]
**Problem discovery update:**

It seems that the params["id"] isn't available (it's coming "" :()

**Comment by RubenMateus** [comment]
is this still happening?

**Comment by clucasalcantara** [comment]
This was happening when we was using a package approach to split the bookings service from the `main.go`. 

Currently is working but the goal is to have a folder where we can organize the DAO/CRUD methods and keep them away from the main program.

**Comment by RubenMateus** [comment]
Sure i can split this up, can you give me some goals/acceptance criteria?
Like: 
- [ ] Split handlers to separate file.
- [ ] Split routes to separate file.
- [ ] Split the structs into separate files inside the models folder?
...

**Comment by clucasalcantara** [comment]
Sure! I'll add the details at the description :)

**Comment by clucasalcantara** [comment]
I've added a new issue instead, please follow there #6
