### ISSUE TITLE
[Discussion] Improve concern separation / Folder structure

### ISSUE THREAD

**Issue by clucasalcantara** [hexis-hub/hexis-bookings-api#6]
It's a good idea to work this API as one service in a group.

Thinking about the main goal we gonna need a mongo connection, a group of models, some constants and config variables and a layer to interact with the database to query. I think that we can use a package pattern approach and compose the API program with each one of them (one for database operations, one for controller actions, blowing ideas to the air... )

How can we organize this module?

**Comment by RubenMateus** [comment]
Packages:
- [x] Route Handlers to separate file.
- [x] Routes to separate file.
- [x] Models
- [ ] Data access layer (mongo) #1 

Also note that maybe we should use this lib for uuid's -> https://github.com/google/uuid (also done)

**Comment by clucasalcantara** [comment]
Yeah, sure! Just remember to add the package using glide to keep the dep management

**Comment by RubenMateus** [comment]
hum, i think glide is going to be deprecated
https://github.com/Masterminds/glide#golang-dep

`The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep... `

maybe use go's dep, since its embedded in the language since 1.11 (i think)

**Comment by clucasalcantara** [comment]
News everyday! shausua Awesome! let's do this! I'll assignee this issue for u so?

**Comment by RubenMateus** [comment]
sure i can give it a try
